# Nighty_Code Default Configuration

scanner:
  ignore_patterns:
    - "*.pyc"
    - "__pycache__"
    - ".git"
    - ".venv"
    - "venv"
    - "node_modules"
    - ".idea"
    - ".vscode"
  
  max_file_size_mb: 10
  follow_symlinks: false
  scanignore_filename: ".scanignore"  # Custom ignore file name

classifier:
  extensions:
    python: [".py", ".pyw"]
    yaml: [".yaml", ".yml"]
    json: [".json"]
    markdown: [".md", ".markdown"]
    
parser:
  timeout_seconds: 30
  max_file_lines: 10000

storage:
  output_dir: "output"
  cache_dir: "cache"